### PR TITLE
Decelerate for traffic lights

### LINKED ISSUE #4: Decelerate for traffic-lights
Waypoint Updater node subscribes to /vehicle/traffic_lights topic, find nearest TL ahead and decelerate to stop at the stop-line if it’s “red”. Use traffic light status from simulator until our own classification is implemented. The implementation of deceleration in this issue can be somewhat primitive, e.g. without any physical consideration, as long as it gets the job done. There is an optional follow up issue #8 to improve the deceleration.

### PR DESCRIPTION
**Pull request by misaksson**
Resolves #4

### CODE REVIEW

**Comment by jonam85** [comment]
Not Reviewed

**Comment by jonam85** [comment]
Not Reviewed but closing so you can perform your activities.

**Comment by misaksson** [comment]
Reopen to be able to do the merge.

**Comment by misaksson** [comment]
Merged without review approval using my administrator privileges. The change will be reviewed later on by @jonam85

**Pull request merged**
